name: Track Docs Changes
on:
  push:
    paths:
      - 'docs/**'
    branches:
      - 'main'
jobs:
  build:
    if: github.repository == 'MAA1999/M9A'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "检测到 docs/ 文件变更！"
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.pat }}" \
            -d '{"event_type":"md_changes"}' \
            "https://api.github.com/repos/MAA1999/M9A-WEB/dispatches"
